# Site settings
title: miri4ech
author: miri4ech
keywords: "programming, miri4ech, web Developer, JavaScript, Ruby"
description: "Web Developer in Japan"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://miri4ech.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Social Links
#email:             email
#google.plus:        username
twitter:            miri4ech
#facebook:           username
github:             miri4ech
# stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          miri56
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# twitter_username: miri4ech 
# github_username:  miri4ech

timezone: "Asia/Tokyo"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed

